### ISSUE TITLE
It is actually possible for obj.constructor to be undefined

### ISSUE THREAD

**Issue by tandrewnichols** [JamesHight/node-config-extend#4]
There are cases when `{}.constructor` is undefined. I don't know exactly what these are. Possibly something related to `Object.create`. At any rate, these lines:

```
    var has_own                   = {}.hasOwnProperty;
    var has_own_constructor       = has_own.call( obj, 'constructor' );
    var has_is_property_of_method = has_own.call( obj.constructor.prototype, 'isPrototypeOf' );

    // Not own constructor property must be Object
    if( obj.constructor &&
      !has_own_constructor &&
      !has_is_property_of_method ){
      
      return false;
    }
```

and specifically the third line (`var has_is_property_of_method`) assumes that `obj.constructor` will be there. I think this is simply by oversight because the if statement later _does_ check for an existing `obj.constructor`. The problem is the third line is trying to access `prototype` on `obj.constructor` prior to the check. This is currently blowing up in our app because some recent version of `cookie-parser` (used by express) sets `req.cookies` to an empty object with an undefined constructor when there are no cookies present. So we get an error to the effect of `Cannot read property "prototype" of undefined`.

I don't mind putting in a fix for this, but I wasn't sure what you preferred by way of implementation. My first inclination is to think that you don't really need to save these as Booleans. I would personally just write them all inline like this:

```
    var has_own                   = {}.hasOwnProperty;

    // Not own constructor property must be Object
    if( obj.constructor &&
      !has_own.call(obj, 'constructor') &&
      !has_own.call(obj.constructor.prototype, 'isPrototypeOf') ){
      
      return false;
    }
```

because then the short circuit logic would prevent trying to access `prototype` if `obj.constructor` was undefined. However, if you want to keep these as Boolean vars, you could do this instead:

```
    var has_own                   = {}.hasOwnProperty;
    var has_own_constructor       = has_own.call( obj, 'constructor' );
    var has_is_property_of_method = has_own_constructor && has_own.call( obj.constructor.prototype, 'isPrototypeOf' );

    // Not own constructor property must be Object
    if( obj.constructor &&
      !has_own_constructor &&
      !has_is_property_of_method ){
      
      return false;
    }
```

Thoughts on how you'd prefer to see this implemented?

**Comment by tandrewnichols** [comment]
For what it's worth, someone did open an issue on `cookie-parser`, which Doug Wilson marked as Won't Fix: https://github.com/expressjs/cookie-parser/issues/16. I do think his reasoning is valid, especially as it is not that hard to work around.

**Comment by JamesHight** [comment]
Hi Andrew, 

Can you check if the bug/obj.constructor-check branch resolves your issue?

**Comment by tandrewnichols** [comment]
Yes, that works perfectly.

**Comment by JamesHight** [comment]
v0.1.1 package published with fix.

**Comment by tandrewnichols** [comment]
Fantastic, thanks for the quick fix!
